version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: library-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: library_mgmt
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: library-web
    command: gunicorn library_management_system.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_NAME: "library_mgmt"
      DB_USER: "library_user"
      DB_PASSWORD: "library_pass"
      DB_HOST: "db"
      DB_PORT: "3306"
      ALLOWED_HOSTS: "*"
    depends_on:
      - db

volumes:
  db_data:
