apiVersion: v1
kind: Service
metadata:
  name: library-db
  labels:
    app: library-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: library-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-db
  labels:
    app: library-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-db
  template:
    metadata:
      labels:
        app: library-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: p@ssw0rd
            - name: MYSQL_DATABASE
              value: library_mgmt
            - name: MYSQL_USER
              value: library_user
            - name: MYSQL_PASSWORD
              value: library_pass
          ports:
            - containerPort: 3306