name: CI/CD - Library Management System

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/library-management-system:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/library-management-system:${{ github.sha }}

      - name: Update Helm values.yaml
        run: |
          yq -i '.image.repository = "${{ secrets.DOCKERHUB_USERNAME }}/library-management-system"' deploy/chart/library-management-system/values.yaml
          yq -i '.image.tag = "${{ github.sha }}"' deploy/chart/library-management-system/values.yaml

      - name: Commit updated values.yaml
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add deploy/chart/library-management-system/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push
